# Generated by Django 4.2 on 2023-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=1)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("street", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
            ],
        ),
    ]
