# Generated by Django 4.2 on 2023-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "lab_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("lab_name", models.CharField(max_length=100)),
                ("lab_address", models.CharField(max_length=200)),
                ("lab_phone", models.CharField(max_length=15)),
            ],
        ),
    ]
