# Generated by Django 4.2 on 2023-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0002_lab"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "doctor_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("doctor_number", models.CharField(max_length=15)),
            ],
        ),
    ]
