# Generated by Django 4.2 on 2023-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0004_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doctor_password",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="lab_password",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
