# Generated by Django 4.2 on 2023-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0005_doctor_doctor_password_lab_lab_password_patient_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doctor_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lab",
            name="lab_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
