# Generated by Django 4.2 on 2023-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0007_alter_doctor_doctor_password_alter_lab_lab_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="report_pdf",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
