# Generated by Django 4.2 on 2023-09-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HealthApp", "0008_reports_report_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("prescription_link", models.URLField(max_length=500)),
                ("test_required", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthApp.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthApp.patient",
                    ),
                ),
            ],
        ),
    ]
